steps:

# Build hello-app:1.0.
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-west2-docker.pkg.dev/level-abode-350117/containers/hello-repo/hello-app:1.0'
    - '.'

# Create back-up of main.go and replace "Version: 1.0.0" with "Version: 2.0.0".
- name: 'bash'
  args:
    - '-c'
    - 'cp -p hello-app/main.go hello-app/main.go.bak && sed "s/Version: 1.0.0/Version: 2.0.0/g" hello-app/main.go.bak > hello-app/main.go'

# Build hello-app:2.0.
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/google-samples/hello-app:2.0'
    - '-t'
    - 'us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0'
    - '.'
  dir: 'hello-app'

# Push images.
images:
  - 'gcr.io/google-samples/hello-app:1.0'
  - 'us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0'
  - 'gcr.io/google-samples/hello-app:2.0'
  - 'us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0'
